### ISSUE TITLE
Error when installing the preset

### ISSUE THREAD

**Issue by catwhocode** [takielias/tablar#11]
Error occured after invoking

`php artisan ui tablar:install`

Here's the screenshot

![image](https://github.com/takielias/tablar/assets/6960411/074281f7-dcb7-49df-9c7d-74d1c410a145)

PHP: 8.1.6

**Comment by takielias** [comment]
@catwhocode Thanks for your concern. [Tablar Docs](https://github.com/takielias/tablar/blob/master/README.md) has been updated. Please check & try 

`php artisan tablar:install`
