### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by gerardp** [takielias/tablar#2]
$ php artisan ui tablar:install

   InvalidArgumentException

  Invalid preset.

  at vendor/laravel/ui/src/UiCommand.php:41
     37▕             return call_user_func(static::$macros[$this->argument('type')], $this);
     38▕         }
     39▕
     40▕         if (! in_array($this->argument('type'), ['bootstrap', 'vue', 'react'])) {
  ➜  41▕             throw new InvalidArgumentException('Invalid preset.');
     42▕         }
     43▕
     44▕         if ($this->option('auth')) {
     45▕             $this->call('ui:auth');

      +13 vendor frames
  14  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by takielias** [comment]
Please share your environment, PHP version, and Laravel Version.

**Comment by gerardp** [comment]
I have done a clean installation and it works perfectly, sorry for the inconvenience.
You can close the ticket.
