### ISSUE TITLE
2 body html tags in source code and html structure not correct

### ISSUE THREAD

**Issue by raveiga** [takielias/tablar#36]
Hello.

I installed **Tablar 4.0** in **Laravel 10.31.0**.

- Opening the **/home** url and realising that **inside code** there are 2 **body** html tags.
- Same occurs with a **blank view** like the example in usage:  https://tablar.ebuz.xyz/docs/4.0/usage.
- Same occurs with  **different layouts**:

**Examining the source code of the page, the very top begins with:**

```html
<body>
<div class="page">
    <!-- Top Navbar -->
    <header class="navbar navbar-expand-md d-print-none"
                    data-bs-theme="light"
    >
.... more html code here....

</footer>
    </div>
</div>
</body>
``` 

**And in the middle of the page after the &lt;/body&gt; tag appears:**
```html
<!doctype html>
        <html lang="en">
                <head>
            <meta charset="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
            <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
            
                        
            <title>
                                Tablar                            </title>
            <title>Dashboard</title>
            <!-- CSS files -->
.... more html code here....                    
                            </head>
        <body class="combo" >
                <div class="modal modal-blur fade" id="modal-report" tabindex="-1" role="dialog" aria-hidden="true">

.... more html code here....


```

I tried to export all views and is doing the same.

Any idea, how to fix this?

Thank you.

**Comment by takielias** [comment]
@raveiga Could you please share the View Page source?

**Comment by raveiga** [comment]
Hi, you can see a test page with the default layout like in docs example:

[](https://ficharng.iessanclemente.net:65001/test)

**Comment by takielias** [comment]
@raveiga Thanks for your precious support. Could you please update the package & let me know your feedback?
