### ISSUE TITLE
How does the menu become inactive when another is selected?

### ISSUE THREAD

**Issue by gerardp** [takielias/tablar#4]
![Captura de pantalla 2023-01-13 a las 10 21 55](https://user-images.githubusercontent.com/168353/212289135-f64a3496-ce48-4cf9-8dcd-6dcf3a6ed39e.png)

**Comment by takielias** [comment]
You may check this Class [ActiveChecker](https://github.com/takielias/tablar/blob/master/src/Menu/ActiveChecker.php)
