### ISSUE TITLE
Deprecated Event

### ISSUE THREAD

**Issue by corean** [takielias/tablar#5]
```
Creation of dynamic property TakiElias\Tablar\Tablar::$events is deprecated in /Users/corean/Dropbox/Sites/cccf2/vendor/takielias/tablar/src/Tablar.php on line 60
```
Laravel v10.13.0 (PHP v8.2.5)

**Comment by takielias** [comment]
@corean I could not reproduce the issue. Could you please explain in more detail?

**Comment by corean** [comment]
@takielias 
I looked it up and it's a PHP8.2 issue.
https://stitcher.io/blog/deprecated-dynamic-properties-in-php-82

I switched to php8.1 and got peace of mind. :D

**Comment by takielias** [comment]
@corean I see. Also tried PHP 8.2 but did not get any error yet. Could you please mention exactly when did you get the error?

**Comment by takielias** [comment]
@corean I have added a fix https://github.com/takielias/tablar/commit/3225dc543c66e0caa9661c955cdebbe89cc5f9ad for PHP 8.2 . Please update the packages using `composer update` command.

**Comment by corean** [comment]
@takielias Wow, thank you.
