### ISSUE TITLE
Check if vite is enabled in auth/layout.blade.php

### ISSUE THREAD

**Issue by iz5clj** [takielias/tablar#54]
As you do in vendor/master.blade.php you should also check in vendor/auth/layout.blade.php if vite is enabled.
Good job with this module.

**Comment by takielias** [comment]
@iz5clj Could you please explain in more detail?

**Comment by iz5clj** [comment]
In vendor/master.blade.php you make a check:
`
@if(config('tablar','vite'))
        @vite('resources/js/app.js')
    @endif
`
Would it be also nice to make this check in vendor/auth/layout.blade.php?

**Comment by takielias** [comment]
@iz5clj It's fixed.
