### ISSUE TITLE
Not show icons in navbar

### ISSUE THREAD

**Issue by mariolucasdev** [takielias/tablar#6]
config/tablar.php
![image](https://github.com/takielias/tablar/assets/14020978/6e70167f-1580-4ed0-acf1-a5e605da5ee5)

laravel version:  10

**Comment by takielias** [comment]
Did you inspect the element & any console errors?

**Comment by mariolucasdev** [comment]
Yes, there were no errors and the class of the icon appeared normally. see print screen.

![image](https://github.com/takielias/tablar/assets/14020978/4239fc55-58e0-4cca-8025-028a00c8d26e)

**Comment by takielias** [comment]
In the latest version of Tabler Icon, they removed the ti class support. Now only support SVG. I'm working on it. Will share the update soon.

**Comment by mariolucasdev** [comment]
ok thanks.
