### ISSUE TITLE
Problem with fresh installation of Laravel 11

### ISSUE THREAD

**Issue by pepo-ec** [takielias/tablar#64]
Hello. I have followed the steps to install "Tablar" in a fresh installation of Laravel-11 but when I enter the "Login" or "Register" menus I get errors:

Login:
Call to undefined method App\Http\Controllers\Auth\LoginController::middleware()

Register:
Call to undefined method App\Http\Controllers\Auth\RegisterController::middleware()

Please, is it a bug in "Tablar" or is there some step I'm skipping?

**Comment by takielias** [comment]
@pepo-ec Could you please replace your `controller.php` with the following code?

```<?php

namespace App\Http\Controllers;

abstract class Controller extends \Illuminate\Routing\Controller
{
    //
}
```

**Comment by pepo-ec** [comment]
Yes. I change to:

```php
namespace App\Http\Controllers;

/* abstract class Controller */
abstract class Controller extends \Illuminate\Routing\Controller
{
    //
}
```

And now it works. Thank you!
