### ISSUE TITLE
Issue with <x-flat-picker> component

### ISSUE THREAD

**Issue by RodolVelasco** [takielias/tablar#70]
Not able to set minDate attribute (minDate: "today") to disable all past dates from before today.

**Comment by takielias** [comment]
@RodolVelasco 

Please update [Tablar Kit]( https://github.com/takielias/tablar-kit) and try using the following code snippet 

```
<x-flat-picker name="birth_date"
               :options="['minDate' => now()->format('Y-m-d')]"
               class="mb-3"></x-flat-picker>
```

**Comment by takielias** [comment]
You may check https://youtu.be/zyShcQ2e5T4

**Comment by RodolVelasco** [comment]
Thanks for your quick response. Sadly, I was not able to make it work. I updated tablar.kit as suggested in the video and documentation. Then tried multiple ways with :options="['minDate' => now()->format('Y-m-d')]" and with :jsonOptions too. x-flat-picker works fine with the default behaviour but no success when given :options attribute

**Comment by takielias** [comment]
@RodolVelasco, sorry for the inconvenience. I have also updated to Tablar 10.01. Please update it and let me know your feedback.

**Comment by RodolVelasco** [comment]
Awesome. Thanks for your quick response. Now is working perfectly!
